image:
  name: circleci/ruby:2.5-node-browsers

stages:
  - test
  - deploy

test:
  stage: test
    script:
      make html API_SPEC=source/v1/openapi.yaml

deploy_dev:
  stage: deploy
  script:
    - curl -v -L -o cf-cli_amd64.deb 'https://cli.run.pivotal.io/stable?release=debian64&source=github'
    - sudo dpkg -i cf-cli_amd64.deb
    - cf -v
    - curl -v -L -o autopilot https://github.com/contraband/autopilot/releases/download/0.0.3/autopilot-linux
    - chmod +x autopilot
    - cf install-plugin autopilot -f
    - CF_SPACE=development CF_APP=tariff-api-dev ./bin/deploy
  only:
    - master

deploy_production:
  stage: deploy
  script:
    - curl -v -L -o cf-cli_amd64.deb 'https://cli.run.pivotal.io/stable?release=debian64&source=github'
    - sudo dpkg -i cf-cli_amd64.deb
    - cf -v
    - curl -v -L -o autopilot https://github.com/contraband/autopilot/releases/download/0.0.3/autopilot-linux
    - chmod +x autopilot
    - cf install-plugin autopilot -f
    - CF_SPACE=production CF_APP=tariff-api-production ./bin/deploy
  when: manual
  only:
  	- production
